twig:
    default_path: '%kernel.project_dir%/templates'
    
    globals:
        # the value is the service's id
        genres: '@App\Controller\HomeController'

    form_themes:
        ['bootstrap_5_horizontal_layout.html.twig']

when@test:
    twig:
        strict_variables: true
