vich_uploader:
    db_driver: orm

    mappings:
        manuscripts:
            uri_prefix: /images/manuscripts
            upload_destination: '%kernel.project_dir%/public/images/manuscripts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
    metadata:
        type: attribute
